apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zookeeper-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "zookeeper-operator.commonLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "zookeeper-operator.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "zookeeper-operator.fullname" . }}
        component: zookeeper-operator
      {{- if .Values.annotations }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ template "zookeeper-operator.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6000
          name: metrics
        command:
        - zookeeper-operator
        env:
        - name: WATCH_NAMESPACE
          value: "{{ .Values.watchNamespace }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ template "zookeeper-operator.fullname" . }}
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
{{- if .Values.logForward.create }}
      - name: {{ .Values.splunk.fluentBit.name }}
        image: "{{ .Values.splunk.fluentBit.image.repository }}:{{ .Values.splunk.fluentBit.image.tag }}"
        imagePullPolicy: {{ .Values.splunk.fluentBit.image.pullPolicy }}
        {{- if .Values.splunk.fluentBit.resources }}
        resources:
{{ toYaml .Values.splunk.fluentBit.resources | indent 10 }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.splunk.fluentBit.port }} # metrics endpoint is ${POD_IP}:2020/api/v1/metrics/prometheus
        volumeMounts:
          - name: fluent-bit-config
            mountPath: /fluent-bit/etc
          - name: logging-volume
            mountPath: /logging-volume
          - name: fluent-data
            mountPath: /var/fluent-bit
        env:
        - name: SPLUNK_HOST
          value: "{{ .Values.splunk.host }}"
        - name: SPLUNK_PORT
          value: "{{ .Values.splunk.port }}"
        - name: SPLUNK_INDEX
          value: "{{ .Values.splunk.index }}"
        - name: SPLUNK_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.splunk.token }}
              key: token
        - name: SPLUNK_SOURCE
          value: {{ .Values.splunk.source }}
        - name: POD_UID_FLUENT_BIT
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SPLUNK_SOURCETYPE
          value: {{ .Values.splunk.sourceType }}
        - name: CONTAINER_RUNTIME
          value: {{ .Values.splunk.containerRuntime }}
      volumes:
        - name: fluent-bit-config
          configMap:
            name: {{ .Values.splunk.fluentBit.name }}-configmap
        - name: logging-volume
          emptyDir: {}
        - name: fluent-data
          emptyDir: {}
      imagePullSecrets:
{{- range (default .Values.global.imagePullSecrets .Values.splunk.fluentBit.image.imagePullSecrets ) }}
      - name: {{ . }}
{{- end }}
{{- range (default .Values.global.imagePullSecrets .Values.serviceAccount.imagePullSecrets ) }}
      - name: {{ . }}
{{- end }}
{{- end }}
