name: ci
permissions:
  contents: read

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
        id: go
      - name: Set up Go for root
        run: |
          sudo ln -sf `which go` `sudo which go` || true
          sudo go version

      - name: Check values schema json
        uses: losisin/helm-values-schema-json-action@v3
        with:
          values: values.yaml
          working-directory: charts/zookeeper-operator
          fail-on-diff: true
      - name: get go version
        run: go version
      - name: Gofmt and License checks
        run: make check
      - name: unit tests
        run: make test
      - name: Build Docker image (no push)
        env:
          DOCKER_BUILDKIT: 1
        run: |
          GO_VERSION=$(awk '/^go /{print $2}' go.mod | cut -d. -f1,2)
          docker build \
            --build-arg VERSION=0.0.0-ci \
            --build-arg GIT_SHA=${GITHUB_SHA::7} \
            --build-arg GO_VERSION=${GO_VERSION} \
            -t zookeeper-operator:ci .
